config/routes.rb
Niftyforms::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :users
  resources :sessions
  resources :forms do
    get 'preview'
    resources :posts
  end

  root to: 'forms#index'
end

app/models/answer.rb
class Answer
  include Mongoid::Document

  embedded_in :post
  belongs_to :form_field
end

app/models/date_answer.rb
class DateAnswer < Answer
end

app/models/date_field.rb
class DateField < FormField
end

app/models/email_answer.rb
class EmailAnswer < Answer
end

app/models/email_field.rb
class EmailField < FormField
end

app/models/file_answer.rb
class FileAnswer < Answer
end

app/models/file_field.rb
class FileField < FormField
end

app/models/form.rb
class Form
  include Mongoid::Document
  include Mongoid::Timestamps

  field :user_id, type: Integer
  field :title
  field :description
  field :badge_background_color

  embeds_many :form_fields
  has_many :posts

  attr_accessible :title, :description, :form_fields
  accepts_nested_attributes_for :form_fields

  before_create :select_badge_background_color

  def as_json options={}
    attrs = super options
    attrs['fields'] = attrs['form_fields']
    attrs.delete 'form_fields'
    attrs['is_new_record'] = new_record?
    attrs
  end

  private

  def select_badge_background_color
    colors = %w{#243567 #3F911D #9D5B22 #44A7D6}
    self.badge_background_color = colors.sample
  end
end

app/models/form_field.rb
class FormField
  include Mongoid::Document

  attr_accessible :label, :required, :helpText, :_type
  attr_accessible :choices

  field :label
  field :required, type: Boolean, default: false
  field :help_text

  embedded_in :form

  def serializable_hash(options = nil)
    hash = super options
    hash['type'] = _type
    hash
  end

  def answer_type
    _type.gsub("Field", "Answer").constantize
  end
end

app/models/money_field.rb
class MoneyField < FormField

end

app/models/phone_field.rb
class PhoneField < FormField

end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps

  embeds_many :answers
  belongs_to :form

  def answer_for_field(field)
    answers.detect { |answer| answer.form_field_id == field.id }
  end
end

app/models/radio_field.rb
class RadioField < FormField
  field :choices, type: Array
end

app/models/text_answer.rb
class TextAnswer < Answer
  attr_accessible :value

  field :value
end

app/models/text_field.rb
class TextField < FormField
end

app/models/time_answer.rb
class TimeAnswer < Answer
end

app/models/time_field.rb
class TimeField < FormField
  field :size
end

app/models/url_answer.rb
class URLAnswer < Answer
end

app/models/url_field.rb
class URLField < FormField

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  validates_presence_of :email
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password

  before_create { generate_token :auth_token }

  def generate_token column
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  respond_to :html, :json

  before_filter :authenticate_user!

  expose(:forms) { Form.where(user_id: current_user.id) }
  expose(:form)

  def index
    respond_with forms
  end

  def show
    respond_with form
  end

  def new
  end

  def edit
  end

  def preview
  end

  def create
    form.user_id = current_user.id
    if form.save
      flash.notice = "Form is created"
    end
    respond_with form
  end

  def update
    if form.save
      flash.notice = "Form is updated"
    end
    respond_with form
  end

  def destroy
    form.destroy
    respond_with form
  end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<div class="container">
  <div class="editor">
    <aside>
      <div class="tabbable">
        <ul class="nav nav-pills" data-bind="tab:selectedTab">
          <li class="active">
            <a href="#addField" data-toggle="tab">Add a Field</a>
          </li>
          <li><a href="#fieldSettings" data-toggle="tab">Field Settings</a></li>
          <li><a href="#formSettings" data-toggle="tab">Form Settings</a></li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="addField">
            <ul class="unstyled fields" data-bind="foreach:catalog.items">
              <li>
                <button data-bind="click:$root.addFieldWithCatalogItem, text:label" class="btn"></button>
              </li>
            </ul>
          </div>
          <div class="tab-pane" id="fieldSettings">
            <div data-bind="if:selectedField">
              <div data-bind="template:{name:'BaseFieldSettingsTemplate',data:selectedField}"></div>
            </div>
            <div data-bind="ifnot:selectedField">
              Select a field.
            </div>
          </div>
          <div class="tab-pane" id="formSettings">
            <div data-bind="template:{name:'FormSettingsTemplate', data:form}"></div>
          </div>
        </div>
      </div>
    </aside>
    <section class="main">
      <div data-bind="click:showFormSettings,
                      css:{selected: $root.isFormSettingsActive()}">
        <h2 data-bind="text:form.title"></h2>
        <p data-bind="text:form.description"></p>
      </div>

      <div data-bind="with:form">
        <div data-bind="template:{name:'BaseFieldPreviewTemplate', foreach:fields},
                        sortableList:fields"></div>
      </div>

      <button class="btn" data-bind="click:save">Save</button>

      <br><br><br>
      <pre data-bind="text:toJSON"></pre>
    </section>
  </div>
</div>

<!-- Form settings -->
<script type="text/html" id="FormSettingsTemplate">
  <label for="form_title">Form title</label>
  <input data-bind="value:title, valueUpdate:'afterkeydown'">

  <label for="form_description">Description</label>
  <textarea data-bind="value:description,  valueUpdate:'afterkeydown'" class="form_description"></textarea>
</script>

<!-- Generic field settings template renders common field options -->
<script type="text/html" id="BaseFieldSettingsTemplate">
  <div class="field-settings">
    <label>Field label</label>
    <textarea data-bind="value:label, valueUpdate:'afterkeydown'" class="field_label"></textarea>

    <label class="checkbox">
      Required?
      <input type="checkbox" data-bind="checked:required">
    </label>

    <label>Help text</label>
    <textarea data-bind="value:helpText"></textarea>

    <div data-bind="template:settingsTemplate()"></div>
  </div>
</script>

<!-- Helper template for rendering choiceable field types -->
<script type="text/html" id="ChoicesTemplate">
  <div class="clearfix">
    <label>Choices</label>
    <ul data-bind="foreach:choices" class="unstyled">
      <li>
        <input data-bind="value:value,valueUpdate:'afterkeydown'" class="span1">
        <input data-bind="value:text,valueUpdate:'afterkeydown'" class="span2">
        <button data-bind="click:$parent.addChoice" class="btn btn-mini">+</button>
        <button data-bind="click:$parent.removeChoice" class="btn btn-mini">×</button>
      </li>
    </ul>
    <div data-bind="ifnot: hasChoices">
      <button data-bind="click:addChoice" class="btn">+ Add a Choice</button>
    </div>
  </div>
  <div class="clearfix">
    <label class="checkbox">
      <input data-bind="checked:randomized" type="checkbox">
      <span>Randomized?</span>
    </label>
  </div>
</script>

<!-- Settings templates for each field type -->
<script type="text/html" id="TextFieldSettingsTemplate">
  <label>Field size</label>
  <select data-bind="options:availableSizes, value:size"></select>
</script>

<script type="text/html" id="TextareaFieldSettingsTemplate">
</script>

<script type="text/html" id="NumberFieldSettingsTemplate">
</script>

<script type="text/html" id="CheckboxFieldSettingsTemplate">
  <div data-bind="template:'ChoicesTemplate'"></div>
</script>

<script type="text/html" id="RadioFieldSettingsTemplate">
  <div data-bind="template:'ChoicesTemplate'"></div>
</script>

<script type="text/html" id="SelectFieldSettingsTemplate">
  <div data-bind="template:'ChoicesTemplate'"></div>
</script>

<script type="text/html" id="ShortNameFieldSettingsTemplate">
</script>

<script type="text/html" id="PhoneFieldSettingsTemplate">
</script>

<script type="text/html" id="FileFieldSettingsTemplate">
</script>

<script type="text/html" id="AddressFieldSettingsTemplate">
</script>

<script type="text/html" id="DateFieldSettingsTemplate">
</script>

<script type="text/html" id="EmailFieldSettingsTemplate">
</script>

<script type="text/html" id="TimeFieldSettingsTemplate">
</script>

<script type="text/html" id="URLFieldSettingsTemplate">
</script>

<script type="text/html" id="MoneyFieldSettingsTemplate">
</script>

<script type="text/html" id="LikertFieldSettingsTemplate">
</script>


<!-- Base preview template for fields -->
<script type="text/html" id="BaseFieldPreviewTemplate">
  <div class="field-preview"
       data-bind="click:$root.showFieldSettings,
                  css:{selected: $data == $root.selectedField()},
                  sortableItem: $data">
    <div data-bind="text:label" class="field-label"></div>
    <div data-bind="template:previewTemplate()"></div>
    <div class="action-buttons">
      <button data-bind="click:$root.duplicateField" class="btn btn-mini btn-info">
        <i class="icon-plus icon-white"></i>
      </button>
      <button data-bind="click:$root.removeField" class="btn btn-mini btn-danger">
        <i class="icon-remove icon-white"></i>
      </button>
    </div>
    <br>
  </div>
</script>

<!-- Preview templates for each field type -->
<script type="text/html" id="TextFieldPreviewTemplate">
  <input class="span4">
</script>

<script type="text/html" id="TextareaFieldPreviewTemplate">
  <textarea></textarea>
</script>

<script type="text/html" id="NumberFieldPreviewTemplate">
  <input class="span4">
</script>

<script type="text/html" id="CheckboxFieldPreviewTemplate">
  <ul data-bind="foreach:choices" class="unstyled">
    <li>
      <label class="checkbox">
        <input type="checkbox" disabled readonly>
        <span data-bind="text:text"></span>
      </label>
    </li>
  </ul>
</script>

<script type="text/html" id="RadioFieldPreviewTemplate">
  <ul data-bind="foreach:choices" class="unstyled">
    <label class="radio">
      <input type="radio" disabled readonly>
      <span data-bind="text:text"></span>
    </label>
  </ul>
</script>

<script type="text/html" id="SelectFieldPreviewTemplate">
  <select data-bind="options:choices, optionsText:'text'" disabled readonly></select>
</script>

<script type="text/html" id="ShortNameFieldPreviewTemplate">
  <label>First</label>
  <input class="span2">

  <label>Last</label>
  <input class="span4">
</script>

<script type="text/html" id="PhoneFieldPreviewTemplate">
  <input class="span4">
</script>

<script type="text/html" id="FileFieldPreviewTemplate">
  FileFieldPreviewTemplate
</script>

<script type="text/html" id="AddressFieldPreviewTemplate">
  <textarea></textarea>
</script>

<script type="text/html" id="DateFieldPreviewTemplate">
  DateFieldPreviewTemplate
</script>

<script type="text/html" id="EmailFieldPreviewTemplate">
  <input class="span4">
</script>

<script type="text/html" id="TimeFieldPreviewTemplate">
  TimeFieldPreviewTemplate
</script>

<script type="text/html" id="URLFieldPreviewTemplate">
  <input class="span4">
</script>

<script type="text/html" id="MoneyFieldPreviewTemplate">
  <input class="span4">
</script>

<script type="text/html" id="LikertFieldPreviewTemplate">
  LikertFieldPreviewTemplate
</script>

app/views/forms/edit.html.erb
<%= render "form", form: form %>

<%= javascript_tag do %>
window.initialFormData = <%=raw form.to_json %>;
<% end %>

app/views/forms/index.html.erb
<div class="container">
  <h1>My Forms</h1>

  <div class="form-index-container">
    <% forms.to_a.in_groups_of(3, false) do |frms| %>
      <div class="row">
      <% frms.each do |form| %>
        <%= link_to edit_form_path(form) do %>
        <div class="span4" style="background-color: <%= form.badge_background_color %>">
          <h3><%= form.title %></h3>
          <!-- <p><%= form.description %></p> -->
          <p class="info">Last updated <%= time_ago_in_words form.updated_at %> ago</p>
          <div class="pull-right" style="display:none">
            <%= link_to edit_form_path(form), :class => 'btn btn-info btn-small' do %>
              <i class="icon-edit icon-white"></i> Edit
            <% end %>
          </div>
        </div>
        <% end %>
      <% end %>
      </div>
    <% end %>
  </div>

<style type="text/css" media="screen">
  .form-index-container .span4 {
    background-color: #243567;
    padding: 15px;
    width: 260px;
    height: 80px;
    margin: 0px 20px 10px 0px;
  }

  .form-index-container .span4 h3 {
    font-weight: 300;
    color: #fff;
    margin-bottom: 0.2em;
    line-height: 1em;
  }

  .form-index-container .span4 p {
    color: #f0f0f0;
    margin-bottom: 0.1em;
  }

  .form-index-container .span4 p.info {
/*    color: #909BFF;*/
  }

  .form-index-container a:hover {
    text-decoration: none;
  }
</style>

app/views/forms/new.html.erb
<%#= debug form.to_json %>

<%= render "form", form: form %>

<%= javascript_tag do %>
window.initialFormData = <%=raw form.to_json %>;
<% end %>

app/views/forms/show.html.erb
<div class="form">
  <h1><%= form.title %></h1>
  <addr><%= form.description %></addr>

  <ul class="fields">
  <% form.form_fields.each do |field| %>
    <li>
      <%= render partial: "fields/#{field._type.underscore}",
                 locals: {field: field} %>
    </li>
  <% end -%>
  </ul>
</div>