config/routes.rb
Niftyforms::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  resources :users
  resources :sessions
  resources :forms do
    get 'preview'
    resources :posts
  end

  root to: 'forms#index'
end

app/models/answer.rb
class Answer
  include Mongoid::Document

  embedded_in :post
  belongs_to :form_field
end

app/models/date_answer.rb
class DateAnswer < Answer
end

app/models/date_field.rb
class DateField < FormField
end

app/models/email_answer.rb
class EmailAnswer < Answer
end

app/models/email_field.rb
class EmailField < FormField
end

app/models/file_answer.rb
class FileAnswer < Answer
end

app/models/file_field.rb
class FileField < FormField
end

app/models/form.rb
class Form
  include Mongoid::Document
  include Mongoid::Timestamps

  field :user_id, type: Integer
  field :title
  field :description
  field :badge_background_color

  embeds_many :form_fields
  has_many :posts

  attr_accessible :title, :description, :form_fields
  accepts_nested_attributes_for :form_fields

  before_create :select_badge_background_color

  def as_json options={}
    attrs = super options
    attrs['fields'] = attrs['form_fields']
    attrs.delete 'form_fields'
    attrs['is_new_record'] = new_record?
    attrs
  end

  private

  def select_badge_background_color
    colors = %w{#243567 #3F911D #9D5B22 #44A7D6}
    self.badge_background_color = colors.sample
  end
end

app/models/form_field.rb
class FormField
  include Mongoid::Document

  attr_accessible :label, :required, :helpText, :_type
  attr_accessible :choices

  field :label
  field :required, type: Boolean, default: false
  field :help_text

  embedded_in :form

  def serializable_hash(options = nil)
    hash = super options
    hash['type'] = _type
    hash
  end

  def answer_type
    _type.gsub("Field", "Answer").constantize
  end
end

app/models/money_field.rb
class MoneyField < FormField

end

app/models/phone_field.rb
class PhoneField < FormField

end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps

  embeds_many :answers
  belongs_to :form

  def answer_for_field(field)
    answers.detect { |answer| answer.form_field_id == field.id }
  end
end

app/models/radio_field.rb
class RadioField < FormField
  field :choices, type: Array
end

app/models/text_answer.rb
class TextAnswer < Answer
  attr_accessible :value

  field :value
end

app/models/text_field.rb
class TextField < FormField
end

app/models/time_answer.rb
class TimeAnswer < Answer
end

app/models/time_field.rb
class TimeField < FormField
  field :size
end

app/models/url_answer.rb
class URLAnswer < Answer
end

app/models/url_field.rb
class URLField < FormField

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  attr_accessible :email, :password, :password_confirmation

  validates_presence_of :email
  validates_presence_of :password, :on => :create
  validates_confirmation_of :password

  before_create { generate_token :auth_token }

  def generate_token column
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/views/fields/_select_field.html.erb
<label><%= field.label %></label>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>niftyforms</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700&subset=latin,latin-ext"
        rel="stylesheet">
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>">
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">XYZ<!--niftyforms--></a>
        <div class="nav-collapse">
          <ul class="nav">
            <li class="active"><%= link_to "My Forms", forms_path %></li>
            <li><%= link_to "Add New Form", new_form_path %></li>
          </ul>
        </div>
        <div class="pull-right">
          <% if current_user %>
            Logged in as <%= current_user.email %>.
            <%= link_to "Log out", logout_path %>
          <% else %>
            <%= link_to "Sign up", signup_path %> or
            <%= link_to "log in", login_path %>.
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>
  <%= javascript_include_tag "application" %>
</body>
</html>